{
 "title": "Water Meter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "flowgpm" } },
   "targets": [
    {
     "database": "\"watermeter\"",
     "measure": "Consumption",
     "rawQuery": "SELECT \n  MIU,\n  bin(time, 15m) as time, \n\tmeasure_value::bigint as consumption, \n\tLAG(measure_value::bigint, 3) OVER (\n\t\tORDER BY BIN(time, 15m)\n\t\t) as prev,\n\tLAG(time, 3) OVER (\n\t\tORDER BY BIN(time, 15m)\n\t\t) as prev_time\nFROM $__database.$__table \nWHERE $__timeFilter -- AND MIU = '1655905322'\nORDER BY time DESC LIMIT 2000",
     "table": "\"1544905322\""
    }
   ]
  },
  {
   "title": "Recent Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "flowgpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"watermeter\"",
     "measure": "Consumption",
     "rawQuery": "SELECT \n  time as time, \n\tmeasure_value::bigint as consumption\nFROM $__database.$__table\nWHERE $__timeFilter\nORDER BY time desc\nLIMIT 100",
     "table": "\"1544905322\""
    }
   ]
  },
  {
   "title": "Water Meter Consumption Reading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "gallons" } },
   "targets": [
    {
     "database": "\"watermeter\"",
     "measure": "Consumption",
     "rawQuery": "SELECT time, measure_value::bigint \nFROM $__database.$__table \nWHERE $__timeFilter\nORDER BY time DESC LIMIT 2000",
     "table": "\"1544905322\""
    }
   ]
  },
  {
   "title": "Estimated Bill",
   "type": "stat",
   "description": "Based on average usage for 60 measurements",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "CCF/month" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"watermeter\"",
     "measure": "Consumption",
     "rawQuery": "SELECT \n  bin(time, 15m) as time, \n\tmeasure_value::bigint as consumption, \n\tLAG(measure_value::bigint, 300) OVER (\n\t\tORDER BY BIN(time, 15m)\n\t\t) as prev,\n\tLAG(time, 300) OVER (\n\t\tORDER BY BIN(time, 15m)\n\t\t) as prev_time\nFROM $__database.$__table ORDER BY time DESC LIMIT 1",
     "table": "\"1544905322\""
    }
   ]
  }
 ]
}